@startuml Melihat List Ticket

hide footbox

' title "Melihat List Ticket"

actor EU as "__: External User__"
boundary TicketPage as "__: TicketPage__"
control TicketController as "__: TicketController__"
entity Users as "__: Users__"
entity Employees as "__: Employees__"
entity Ticket as "__: Ticket__"
entity TicketMember as "__: TicketMember__"
entity ProductMembers as "__: Product Members__"
' entity ProductMemberRoles as "__: Product Member Roles__"
entity TicketCategories as "__: Ticket Categories__"
entity TicketStatuses as "__: Ticket Statuses__"
entity TicketPriorities as "__: Ticket Priorities__"
' entity Products as "__: Products__"
' entity Companies as "__: Companies__"

autonumber 1
EU -> TicketPage: membuka halaman list ticket
activate TicketPage

TicketPage -> TicketController: getUserTickets()
activate TicketController

TicketController -> Users: getCurrentUser()
activate Users

Users -> TicketController: current user
deactivate Users

TicketController -> Employees: getCurrentEmployee()
activate Employees

Employees -> TicketController: current employee
deactivate Employees

TicketController -> ProductMembers: getCurrentEmployeeAssignedProductMembers()
activate ProductMembers

ProductMembers -> TicketController: current employee product member datas
deactivate ProductMembers

TicketController -> TicketMember: getCurrentProductMemberTicketMember()
activate TicketMember

TicketMember -> TicketController: current product member's ticket member
deactivate TicketMember

TicketController -> Ticket: getTickets()
activate Ticket

Ticket --> TicketController : Tickets
deactivate Ticket

TicketController -> TicketCategories: getTicketCategories()
activate TicketCategories

TicketCategories --> TicketController : Ticket categories
deactivate TicketCategories

TicketController -> TicketStatuses: getTicketStatuses()
activate TicketStatuses

TicketStatuses --> TicketController : TicketStatuses
deactivate TicketStatuses

TicketController -> TicketPriorities: getTicketPriorities()
activate TicketPriorities

TicketPriorities --> TicketController : TicketPriorities
deactivate TicketPriorities

TicketController --> TicketPage : Tickets
deactivate TicketController

TicketPage --> EU : Halaman list ticket
deactivate TicketPage


@enduml
