@startuml Membuat Ticket

hide footbox

' title "Membuat Ticket"

actor EU as "__: External User__"
boundary TicketListPage as "__: Ticket List Page__"
boundary TicketCreatePage as "__: Ticket Create Page__"
control TicketController as "__: Ticket Controller__"
entity Ticket as "__: Ticket__"
entity TicketCategories as "__: Ticket Category__"
entity TicketPriorities as "__: Ticket Priority__"
entity Product as "__: Products__"
entity TicketMember as "__: Ticket Member__"
entity ProductMembers as "__: Product Member__"


autonumber 1
EU -> TicketListPage: Membuka halaman ticket ticket
activate TicketListPage

TicketListPage -> TicketCreatePage: Membuka halaman ticket ticket
activate TicketCreatePage

TicketCreatePage -> TicketController: getTicketRequiredDropdown()
activate TicketController

TicketController -> TicketCategories: getTicketCategories()
activate TicketCategories

TicketCategories --> TicketController : Ticket categories
deactivate TicketCategories

TicketController -> Product: getProducts()
activate Product

Product --> TicketController : Products
deactivate Product


TicketController -> TicketPriorities: getTicketPriorities()
activate TicketPriorities

TicketPriorities --> TicketController : TicketPriorities
deactivate TicketPriorities

TicketController --> TicketCreatePage: dropdownData
deactivate TicketController


' EU -> TicketCreatePage: Mengisi field ticket
' activate TicketCreatePage

TicketCreatePage -> TicketController: createTicket()
activate TicketController

TicketController -> TicketController: validate()
TicketController -> TicketController: setStatusToPending()

TicketController -> ProductMembers: getProductMembers()
activate ProductMembers

ProductMembers --> TicketController : ProductMembers
deactivate ProductMembers

TicketController -> Ticket: createTicket()
activate Ticket

Ticket --> TicketController : Ticket
deactivate Ticket

TicketController -> TicketMember: createTicketPM()
activate TicketMember

TicketMember --> TicketController : TicketMember
deactivate TicketMember

TicketController -> TicketMember: createTicketPIC()
activate TicketMember

TicketMember --> TicketController : TicketMember
deactivate TicketMember

TicketController --> TicketCreatePage : Ticket
deactivate TicketController

TicketCreatePage --> TicketListPage : Halaman ticket berhasil dibuat
deactivate TicketCreatePage

TicketListPage --> EU : Halaman list ticket dengan\nticket yang baru dibuat
deactivate TicketCreatePage


@enduml
