@startuml Melihat Detail Ticket

title "Melihat Detail Ticket"

actor IPM as "__: Product Manager__"
boundary TicketPage as "__: TicketPage__"
control TicketController as "__: TicketController__"
entity Ticket as "__: Ticket__"

autonumber 1
'list
' IPM -> TicketPage: Membuka halaman list ticket
' activate TicketPage

' TicketPage -> IPM: Halaman list ticket
' deactivate TicketPage

'detail
IPM -> TicketPage: Memilih ticket
activate TicketPage


TicketPage -> TicketController: getTicket()
activate TicketController

TicketController -> Ticket: getTicket()
activate Ticket

Ticket --> TicketController : Ticket
deactivate Ticket

TicketController --> TicketPage : Ticket
deactivate TicketController

TicketPage --> IPM : Halaman detail ticket
deactivate TicketPage


@enduml
