@startuml Memverifikasi Ticket

hide footbox

' title "Memverifikasi Ticket"

actor IPM as "__: Product Manager__"
boundary TicketDetailsPage as "__: Ticket Details Page__"
boundary TicketVerifyForm as "__: Ticket Verify Form__"
control TicketController as "__: Ticket Controller__"
entity Ticket as "__: Ticket__"
entity ProductMember as "__: Product Member__"
entity TicketMember as "__: Ticket Member__"

autonumber 1
'list
IPM -> TicketDetailsPage: Memilih ticket
activate TicketDetailsPage

TicketDetailsPage --> IPM: Halaman detail ticket

'Pilih member
TicketDetailsPage -> TicketVerifyForm: Verify Ticket
activate TicketVerifyForm

TicketVerifyForm -> TicketController: getProductDevelopers()
activate TicketController

TicketController -> ProductMember: getProductDevelopers()
activate ProductMember

ProductMember --> TicketController: product developers
deactivate ProductMember

TicketController --> TicketVerifyForm: product developers
deactivate TicketController


TicketVerifyForm --> IPM: Popup memilih developer

IPM -> TicketVerifyForm: Submit developer

TicketVerifyForm -> TicketController: verifyTicket()
activate TicketController

TicketController -> TicketController: validate()

TicketController -> TicketMember: assignTicketMember()
activate TicketMember

TicketMember --> TicketController: ticket member
deactivate TicketMember

TicketController -> Ticket: setTicketStatus()
activate Ticket

Ticket --> TicketController : Ticket
deactivate Ticket

TicketController --> TicketVerifyForm : Ticket
deactivate TicketController

TicketVerifyForm -> TicketDetailsPage : Menutup menu
deactivate TicketVerifyForm

TicketDetailsPage --> IPM : Halaman detail ticket yang sudah\ndiupdate menjadi in progress
deactivate TicketDetailsPage


@enduml
