@startuml Menolak Ticket

' title "Menolak Ticket"
hide footbox

actor IPM as "__: Product Manager__"
boundary TicketDetailsPage as "__: Ticket Details Page__"
boundary TicketRejectPage as "__: Ticket Reject Form__"
control TicketController as "__: Ticket Controller__"
entity Ticket as "__: Ticket__"

autonumber 1
'list
IPM -> TicketDetailsPage: Melihat detail ticket
activate TicketDetailsPage

TicketDetailsPage -> TicketRejectPage : Memilih tombol\nreject Ticket
activate TicketRejectPage


TicketRejectPage -> TicketController: rejectTicket()
activate TicketController

TicketController -> TicketController: validate()

TicketController -> Ticket: setTicketStatus()
activate Ticket

Ticket --> TicketController : Ticket
deactivate Ticket

TicketController --> TicketRejectPage : Pesan ticket berhasil direject
deactivate TicketController

TicketRejectPage --> TicketDetailsPage : Pesan ticket berhasil direject
deactivate TicketRejectPage

TicketDetailsPage --> IPM : Halaman detail ticket\nyang sudah diupdate\nmenjadi rejected
deactivate TicketDetailsPage


@enduml
