@startuml Merevisi Ticket

' title "Menolak Ticket"
hide footbox

actor IPM as "__: Product Manager__"
boundary TicketDetailsPage as "__: Ticket Details Page__"
boundary TicketRevisePage as "__: Ticket Revise Form__"
control TicketController as "__: Ticket Controller__"
entity Ticket as "__: Ticket__"

autonumber 1
'list
IPM -> TicketDetailsPage: Melihat detail ticket
activate TicketDetailsPage

TicketDetailsPage -> TicketRevisePage : Memilih tombol\nRevise
activate TicketRevisePage


TicketRevisePage -> TicketController: reviseTicket(reason)
activate TicketController

TicketController -> TicketController: validate()

TicketController -> Ticket: setTicketStatus()
activate Ticket

Ticket --> TicketController : Ticket
deactivate Ticket

TicketController --> TicketRevisePage : Pesan ticket berhasil direvisi
deactivate TicketController

TicketRevisePage -> TicketDetailsPage : Menutup halaman
deactivate TicketRevisePage

TicketDetailsPage --> IPM : Halaman detail ticket\nyang sudah diupdate\nmenjadi Reviseed
deactivate TicketDetailsPage


@enduml


