@startuml Berkomunikasi Dengan PIC Melalui Whatsapp

' title "Berkomunikasi Dengan PM Melalui Whatsapp"
hide footbox


actor IPM as "__: Product Manager__"
boundary TicketDetailsPage as "__: Ticket Details Page__"
control TicketController as "__: Ticket Controller__"
entity Ticket as "__: Ticket__"
entity TicketMember as "__: Ticket Member__"
entity ProductMember as "__: Product Member__"
entity Employees as "__: Employee__"

autonumber 1
'list
IPM -> TicketDetailsPage: Melihat detail ticket
activate TicketDetailsPage


'Chat
TicketDetailsPage -> TicketController: Menekan Tombol Chat on Whatsapp
activate TicketController

TicketController -> Ticket: getTicket()
activate Ticket

Ticket --> TicketController : Ticket
deactivate Ticket

TicketController -> TicketMember: getTicketMember()
activate TicketMember

TicketMember --> TicketController : TicketMember
deactivate TicketMember

TicketController -> ProductMember: getProductMember()
activate ProductMember

ProductMember --> TicketController : ProductMember
deactivate ProductMember

TicketController -> Employees: getEmployees()
activate Employees

Employees --> TicketController : PIC phone number
deactivate Employees

TicketController -> TicketController : generateTemplateMessage()

TicketController --> TicketDetailsPage : Whapsapp Link
deactivate TicketController

TicketDetailsPage --> IPM : Diarahkan ke Whatsapp Web
deactivate TicketDetailsPage


@enduml
