@startuml Mengubah Status Ticket Menjadi Done

' title "Mengubah Status Ticket Menjadi Done"
hide footbox

actor IPM as "__: Product Manager__"
boundary TicketPage as "__: Ticket Details Page__"
boundary TicketRejectPage as "__: Ticket RejectPage__"
control TicketController as "__: Ticket Controller__"
entity Ticket as "__: Ticket__"

autonumber 1
'list
IPM -> TicketPage: Membuka detail ticket
activate TicketPage

TicketPage -> TicketRejectPage : Memilih tombol\ndone
activate TicketRejectPage


TicketRejectPage -> TicketController: doneTicket()
activate TicketController

TicketController -> TicketController: validate()

TicketController -> Ticket: setTicketStatus()
activate Ticket

Ticket --> TicketController : Ticket
deactivate Ticket

TicketController --> TicketRejectPage : Pesan ticket berhasil diubah
deactivate TicketController

TicketRejectPage --> TicketPage : Pesan ticket\nberhasil berubah\nstatus menjadi done
deactivate TicketRejectPage

TicketPage --> IPM : Halaman detail ticket\nyang sudah diupdate\nmenjadi rejected
deactivate TicketPage


@enduml

