@startuml Mengubah Status Ticket Menjadi Done

' title "Mengubah Status Ticket Menjadi Done"
hide footbox

actor IPM as "__: Product Manager__"
boundary TicketPage as "__: Ticket Details Page__"
control TicketController as "__: Ticket Controller__"
entity Ticket as "__: Ticket__"

autonumber 1
'list
IPM -> TicketPage: Membuka detail ticket
activate TicketPage

TicketPage --> IPM: Halaman detail Ticket


IPM -> TicketPage : Memilih tombol\ndone

TicketPage -> TicketController: doneTicket()
activate TicketController




TicketController -> TicketController: validate()

TicketController -> Ticket: setTicketStatus()
activate Ticket

Ticket --> TicketController : Ticket
deactivate Ticket

TicketController --> TicketPage : Pesan ticket berhasil diubah statusnya menjadi done
deactivate TicketController

' TicketPage -> TicketPage : Pesan ticket berhasil \n berubah status menjadi done

TicketPage --> IPM : Halaman detail ticket yang sudah \n diupdate menjadi rejected
deactivate TicketPage


@enduml

